"""Add stock detail tables

Revision ID: 74c054a265fc
Revises: bf707f9cdd51
Create Date: 2025-11-04 22:17:48.456597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c054a265fc'
down_revision: Union[str, None] = 'bf707f9cdd51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_company_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False, comment='종목 코드'),
    sa.Column('settlement_month', sa.String(length=10), nullable=True, comment='결산월일'),
    sa.Column('listed_shares', sa.BigInteger(), nullable=True, comment='상장주수'),
    sa.Column('listed_capital', sa.BigInteger(), nullable=True, comment='상장자본금액'),
    sa.Column('capital', sa.BigInteger(), nullable=True, comment='자본금'),
    sa.Column('par_value', sa.Integer(), nullable=True, comment='액면가'),
    sa.Column('previous_close', sa.Integer(), nullable=True, comment='전일종가'),
    sa.Column('close_price_change_date', sa.String(length=10), nullable=True, comment='종가변경일자'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_company_info_id'), 'stock_company_info', ['id'], unique=False)
    op.create_index(op.f('ix_stock_company_info_ticker'), 'stock_company_info', ['ticker'], unique=True)
    op.create_table('stock_financial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False, comment='종목 코드'),
    sa.Column('fiscal_year_month', sa.String(length=10), nullable=True, comment='결산년월'),
    sa.Column('current_assets', sa.BigInteger(), nullable=True, comment='유동자산'),
    sa.Column('fixed_assets', sa.BigInteger(), nullable=True, comment='고정자산'),
    sa.Column('total_assets', sa.BigInteger(), nullable=True, comment='자산총계'),
    sa.Column('current_liabilities', sa.BigInteger(), nullable=True, comment='유동부채'),
    sa.Column('fixed_liabilities', sa.BigInteger(), nullable=True, comment='고정부채'),
    sa.Column('total_liabilities', sa.BigInteger(), nullable=True, comment='부채총계'),
    sa.Column('capital_surplus', sa.BigInteger(), nullable=True, comment='자본잉여금'),
    sa.Column('retained_earnings', sa.BigInteger(), nullable=True, comment='이익잉여금'),
    sa.Column('total_equity', sa.BigInteger(), nullable=True, comment='자본총계'),
    sa.Column('revenue', sa.BigInteger(), nullable=True, comment='매출액'),
    sa.Column('cost_of_sales', sa.BigInteger(), nullable=True, comment='매출원가'),
    sa.Column('gross_profit', sa.BigInteger(), nullable=True, comment='매출총이익'),
    sa.Column('net_income', sa.BigInteger(), nullable=True, comment='당기순이익'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_financial_id'), 'stock_financial', ['id'], unique=False)
    op.create_index(op.f('ix_stock_financial_ticker'), 'stock_financial', ['ticker'], unique=False)
    op.create_table('stock_price',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False, comment='종목 코드'),
    sa.Column('current_price', sa.Integer(), nullable=True, comment='현재가'),
    sa.Column('opening_price', sa.Integer(), nullable=True, comment='시가'),
    sa.Column('high_price', sa.Integer(), nullable=True, comment='고가'),
    sa.Column('low_price', sa.Integer(), nullable=True, comment='저가'),
    sa.Column('volume', sa.BigInteger(), nullable=True, comment='거래량'),
    sa.Column('transaction_amount', sa.BigInteger(), nullable=True, comment='거래대금'),
    sa.Column('market_cap', sa.BigInteger(), nullable=True, comment='시가총액'),
    sa.Column('per', sa.Numeric(precision=10, scale=2), nullable=True, comment='PER (주가수익비율)'),
    sa.Column('pbr', sa.Numeric(precision=10, scale=2), nullable=True, comment='PBR (주가순자산비율)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_price_id'), 'stock_price', ['id'], unique=False)
    op.create_index(op.f('ix_stock_price_ticker'), 'stock_price', ['ticker'], unique=False)
    op.create_table('stock_ratios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False, comment='종목 코드'),
    sa.Column('fiscal_year_month', sa.String(length=10), nullable=True, comment='결산년월'),
    sa.Column('revenue_growth_rate', sa.Numeric(precision=10, scale=2), nullable=True, comment='매출액증가율'),
    sa.Column('operating_profit_growth_rate', sa.Numeric(precision=10, scale=2), nullable=True, comment='영업이익증가율'),
    sa.Column('net_income_growth_rate', sa.Numeric(precision=10, scale=2), nullable=True, comment='순이익증가율'),
    sa.Column('roe', sa.Numeric(precision=10, scale=2), nullable=True, comment='ROE (자기자본이익률)'),
    sa.Column('eps', sa.Numeric(precision=10, scale=2), nullable=True, comment='EPS (주당순이익)'),
    sa.Column('sps', sa.Numeric(precision=10, scale=2), nullable=True, comment='주당매출액'),
    sa.Column('bps', sa.Numeric(precision=10, scale=2), nullable=True, comment='BPS (주당순자산)'),
    sa.Column('retention_ratio', sa.Numeric(precision=10, scale=2), nullable=True, comment='유보비율'),
    sa.Column('debt_ratio', sa.Numeric(precision=10, scale=2), nullable=True, comment='부채비율'),
    sa.Column('return_on_assets', sa.Numeric(precision=10, scale=2), nullable=True, comment='총자본순이익률 (ROA)'),
    sa.Column('return_on_equity', sa.Numeric(precision=10, scale=2), nullable=True, comment='자기자본순이익률'),
    sa.Column('net_profit_margin', sa.Numeric(precision=10, scale=2), nullable=True, comment='매출액순이익률'),
    sa.Column('gross_profit_margin', sa.Numeric(precision=10, scale=2), nullable=True, comment='매출액총이익률'),
    sa.Column('stability_debt_ratio', sa.Numeric(precision=10, scale=2), nullable=True, comment='부채비율'),
    sa.Column('borrowing_dependency', sa.Numeric(precision=10, scale=2), nullable=True, comment='차입금의존도'),
    sa.Column('current_ratio', sa.Numeric(precision=10, scale=2), nullable=True, comment='유동비율'),
    sa.Column('quick_ratio', sa.Numeric(precision=10, scale=2), nullable=True, comment='당좌비율'),
    sa.Column('equity_growth_rate', sa.Numeric(precision=10, scale=2), nullable=True, comment='자기자본증가율'),
    sa.Column('total_assets_growth_rate', sa.Numeric(precision=10, scale=2), nullable=True, comment='총자산증가율'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_ratios_id'), 'stock_ratios', ['id'], unique=False)
    op.create_index(op.f('ix_stock_ratios_ticker'), 'stock_ratios', ['ticker'], unique=False)
    op.alter_column('companies', 'ticker',
               existing_type=sa.VARCHAR(length=20),
               comment='종목 코드',
               existing_nullable=False)
    op.alter_column('companies', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment='기업명',
               existing_nullable=False)
    op.drop_constraint('stock_info_company_id_fkey', 'stock_info', type_='foreignkey')
    op.create_foreign_key(None, 'stock_info', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_info', type_='foreignkey')
    op.create_foreign_key('stock_info_company_id_fkey', 'stock_info', 'companies', ['company_id'], ['id'])
    op.alter_column('companies', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='기업명',
               existing_nullable=False)
    op.alter_column('companies', 'ticker',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='종목 코드',
               existing_nullable=False)
    op.drop_index(op.f('ix_stock_ratios_ticker'), table_name='stock_ratios')
    op.drop_index(op.f('ix_stock_ratios_id'), table_name='stock_ratios')
    op.drop_table('stock_ratios')
    op.drop_index(op.f('ix_stock_price_ticker'), table_name='stock_price')
    op.drop_index(op.f('ix_stock_price_id'), table_name='stock_price')
    op.drop_table('stock_price')
    op.drop_index(op.f('ix_stock_financial_ticker'), table_name='stock_financial')
    op.drop_index(op.f('ix_stock_financial_id'), table_name='stock_financial')
    op.drop_table('stock_financial')
    op.drop_index(op.f('ix_stock_company_info_ticker'), table_name='stock_company_info')
    op.drop_index(op.f('ix_stock_company_info_id'), table_name='stock_company_info')
    op.drop_table('stock_company_info')
    # ### end Alembic commands ###
