"""Add market_indices table

Revision ID: eee27c7acc9a
Revises: 74c054a265fc
Create Date: 2025-11-05 18:37:47.928643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eee27c7acc9a'
down_revision: Union[str, None] = '74c054a265fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_indices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='지수 코드 (0001, 1001, NAS, SPX)'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='지수명 (KOSPI, KOSDAQ, NASDAQ, SP500)'),
    sa.Column('current_price', sa.Numeric(precision=20, scale=2), nullable=False, comment='현재가'),
    sa.Column('change_rate', sa.Numeric(precision=10, scale=2), nullable=False, comment='등락률 (%)'),
    sa.Column('change_price', sa.Numeric(precision=20, scale=2), nullable=False, comment='전일대비'),
    sa.Column('timestamp', sa.String(length=20), nullable=False, comment='데이터 시간'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='DB 업데이트 시간'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_indices_code'), 'market_indices', ['code'], unique=True)
    op.create_index(op.f('ix_market_indices_id'), 'market_indices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_indices_id'), table_name='market_indices')
    op.drop_index(op.f('ix_market_indices_code'), table_name='market_indices')
    op.drop_table('market_indices')
    # ### end Alembic commands ###
